---
title: "Curriculum Vitae"
---

```{r}
#| label: setup
#| include: false
library(fontawesome)
```

# Daniel Sánchez Pazmiño

::: {.grid}

::: {.g-col-6}

`r fa('house')` Burnaby, BC, Canada

`r fa('scroll')` Master of Arts in Economics (c)

`r fa('star')` Data Analytics & Causal Inference

:::
  
::: {.g-col-6}


`r fa('envelope')` dsanchezp998@gmail.com

`r fa('language')` English (TOEFL 119/120) & Spanish (Native)

`r fa('terminal')` R, Python & SQL

:::
  
:::  

:::{.callout-tip}
# Summary
Experienced data analyst and applied researcher skilled in R, Python, SQL & Power BI. Focused in providing data-oriented insight with clear and effective communication.
:::

## Education `r fa('graduation-cap')`

-   Simon Fraser University, Master of Arts in Economics (August 2022 - April 2024)

GPA 3.89/4.33. Awarded full funding through an entrance scholarship and teaching assistantships, among 100+ applicants.

-  Universidad San Francisco de Quito, Bachelor of Arts in Finance (Jan 2019 - May 2022)

GPA 3.81/4.00, *magna cum laude*.

-   Bachelor of Arts in Economics, Jan 2017 - Dec. 2021 (Universidad San Francisco de Quito)

GPA 3.82/4.00, *magna cum laude*. Capstone Project: [*Honesty by Convenience: Corruption Tolerance in Ecuador](research.qmd). Awarded best Fall 2021 capstone project. 

## Industry Experience `r fa('suitcase')`

### Junior Data Analyst, Natural Resources Canada

`r fa('calendar')` June 2023 - December 2023

- Co-op student at the Innovation Branch of Natural Resources Canada (federal government of Canada).

- Creation of data visualization, analysis and reporting pipelines and dashboards using Power BI, R and Python.

- Developed presentations and reports for the department’s leadership, using economic and environmental information at the firm, sector, province and national level.

### Corporate Finance Consultant, LVM Consulting

`r fa('calendar')` March 2022 - June 2022

- Assisted in corporate finance consulting on an occasional per-job basis for 10+ projects with large companies in Ecuador.

- Supported the creation of discounted cash flow (DCF) and comparable multiples valuation models in MS Excel.

- Developed business research in the Bloomberg Terminal, S&P Capital IQ and EMIS platforms to calibrate valuations.

### Data Analyst, Milmoh S.L.

`r fa('calendar')` May 2022 - April 2023

- Wrangled, analyzed and visualized data with Power BI, Tableau and R, creating dashboards and reporting pipelines to aid 10+ European clients in business decisions.

- Managed and structured data models with PostgreSQL to deploy and mantain assets in Power BI, Tableau and R.

- Developed reports, code documentation and presented monthly results to clients, including key business insights.

### Finance Intern, Produbanco

`r fa('calendar')` May - July 2018

- Supported the project finance team in the Finance division of one of Ecuador’s largest financial institutions.

- Created dashboards of the Bank's financial performance at the aggregate and branch level

- Developed periodical reports using bank data which eased the communication of bank’s results to the chief financial officer and various department leaders.

### Accounting Intern, Baker Tilly Ecuador

`r fa('calendar')` May - July 2017

- Participated as an intern in the Outsourcing division of an international Top 10 Auditing/Financial Consulting firm.
Aided in the reporting of the clients’ financial information to numerous public entities.

- Attended meetings and training sessions on accounting and finance concepts to be used in the company’s day-to-day activities.

- Translated financial documents from English to Spanish and Spanish to English.

## Technical Skills `r fa('laptop-code')`

- **Multiporpose Scripting**: 
  - R (3+years): *tidyverse, knitr/sweave, infer, caret,* etc. 
  - Python (1 year): `pandas`, `numpy`, `matplotlib`, `scipy`, etc.

- **Dashboarding & Visualisation**:
  - Power BI (1 year)
  - Tableau (1 year)
  - R: *shiny/flexdashboard, ggplot2, plotly, dypgraphs, higcharter*
  - Python: `seaborn`, `matplotlib`, `plotly`. 
  
- **Data Management & Wrangling**:
  - PostgreSQL/SQL Server (1 year)
  - Power Query/Mashup
  - R: *dplyr, data.table, bigmemory*
  - Python: `pandas`
  
- **Document Markup**
  - LaTeX
  - Markdown
  - Quarto
  - RMarkdown
  - Knitr/Sweave

- **0thers**: Git, GitHub, MS Office, Stata, Minitab, MATLAB, Shell, VBA. API access using *selenium, quantmod, wbstats, Quandl, spotifyr, geniusr, lastfmR*, `yfinance`, `wbgapi`, etc. 


## Research Experience & Affiliations `r fa('book-open')`

### Research Associate, ([Laboratorio de Investigación para el Desarrollo del Ecuador](https://laboratoriolide.org/))

`r fa('calendar')` June 2022 - Present

- Co-autorship of research papers with organization members, including a work in progress to be submitted for publication at The Gerontologist International Spotlight Issue.

- Reviewer and maintainer of El Quantificador, LIDE’s blog for short, data-oriented articles on social matters, which involve wrangling, analysis and visualization of data using R. Maintenance of the website in a *blogdown* environment with RStudio. 

- Assisting in the implementation of several of the organization’s projects, including the data analyitcs education program for women of disadvantaged backgrounds, [New Dimensions](https://newdimensions.academy/). 

### Research Intern, Superintendencia de Compañías, Valores y Seguros Ecuador

`r fa('calendar')` January - April 2022

- Contributed to the production of empirical papers and literature reviews, notably, [Family Firms and Economic Performance: A Systematic Literature Review](https://sites.google.com/view/segundocaminom/research-and-publications) with Segundo Camino-Mogro, PhD(c).

- Produced original research using SCVS administrative data, later published in the institution’s peer-reviewed journal, [X-pedientes Económicos](https://ojs.supercias.gob.ec/index.php/X-pedientes_Economicos). 

## [Research](research.qmd) `r fa('book')`

- Sánchez Pazmiño, Daniel. (2023). Honesty by Convenience: Corruption Tolerance in Ecuador. The Philosophy, Politics and Economics Review. https://pressbooks.lib.vt.edu/pper/chapter/article-5/
  - Reproducible code available on [GitHub](https://github.com/dsanchezp18/hbc-v2) and [RPubs](https://rpubs.com/dsanchezp998). 

- Sánchez-Pazmiño, D.H. (2022). Immunizing the Economy: A Causality Discussion on Vaccines and Economic Recovery1. In X-Pedientes Económicos. https://daniel-ec.netlify.app/files/research/immunizing-the-econ.pdf^[The link to the journal's version is usually down, but you may find it [here](https://ojs.supercias.gob.ec/index.php/X-pedientes_Economicos/article/view/103).]
  -  Reproducible code available on [GitHub](https://github.com/dsanchezp18/covidvax-econrecovery-paper) and [RPubs](https://rpubs.com/dsanchezp998). 

## [Other publications](media.qmd) `r fa('comments')`

- Quijano, A. & Sánchez, D. (2023). Homosexuality: what do Ecuadorians think about it? (Original in Spanish: Homosexualidad: ¿que piensan los ecuatorianos?). ISSN 2953-6456. https://elquantificador.org/post/valores/2023-07-02-homosexualidad-qu-piensan-los-ecuatorianos/

- Marchán, A. & Sánchez, D. (2023). Three problems for the quantitative analysis of femicides
in Ecuador (Original in Spanish: Tres problemas para el análisis cuantitativo de los
femicidios en Ecuador). ISSN 2953-6456. https://elquantificador.org/post/valores/2023-03-
07-tres-problemas-para-el-an-lisis-cuantitativo-de-los-femicidios-en-ecuador/.

- Sánchez, D. (2022). A quantitative perspective on the Ecuadorian protests. ISSN 2953-6456.
https://elquantificador.org/post/valores/perspectiva-cuantitativa-protestas-ecuador/

## [Teaching Experience](teaching.qmd) `r fa('chalkboard-user')`

### Teaching Assistant, Simon Fraser University

`r fa('calendar')` Sept. 2022 - Present

- Cooperating with SFU Economics as a TA.in ECON310 Money & Banking (Fall2022), ECON355W Economic Development (Spring 2023) & ECON103 Principles of Microeconomics (Summer 2023).

- Lecturing in tutorials 2-4 times a week with groups of 15-20 students of varying levels of quantitative acumen.

- Coordinating with professors and co-TAs to prepare class seminars, manage the course LMS & attend students during weekly office hours. Creating and grading assignments and exams.

### Private Tutor

`r fa('calendar')` January 2018 - Present

- Aided students across several majors with tutoring sessions in microeconomics, econometrics, statistics, calculus, finance, among others. 

### Teaching Assistant & Instructor, New Dimensions/LIDE

`r fa('calendar')` April 2023 - August 2023 

- Assisted instructors for the Business Analytics for Women education program, New Dimensions, in the SQL and Power BI modules.

- Taught a four hour module on Data Visualisation using Tableau. 

- Coordinating with professors and co-TAs to prepare class seminars, manage the course LMS & attend students during weekly office hours. Creating and grading assignments.

### Teaching Assistant,  Universidad San Francisco de Quito

`r fa('calendar')` Aug. 2020 - Dec. 2021

- Cooperated with USFQ Economics as a TA for courses in Introductory Economics & Austrian School Economics.

- Prepared class seminars, managed the course LMS & attended students during office hours.

- Created and graded assignments and exams and held tutorial sessions 4-5 times a semester.

### Instructor, ECEL Research Group

`r fa('calendar')` April 2021

- Developed and taught Introductory LaTeX course through ECEL Research Group, a USFQ-related academic student body.

- Lectured for 7 hours about LaTeX, facilitating the transmission of complicated programing concepts and exercises to 15-20 participants, using the Overleaf LaTeX interface.

- Developed course materials with LaTeX, available on [GitHub](https://github.com/dsanchezp18/ecel-latex) including applications of the markup language with R and Stata.

## Extracurriculars

### Financial Analysis Volunteer, Universidad San Francisco de Quito

`r fa('calendar')` June 2022

- USFQ Gerontology Community Outreach Project to develop a network of senior-friendly cities in Pichincha, Ecuador.

- Assisted the project leader in the economic and financial studies of several products offered by the organization, as well as market research and sales forecasting.

### Full member, ECEL Research Group

- Participated as a member for an experimental economics oriented academic club based off USFQ’s School of Economics.

- Discussed papers weekly and supported organizing events for the university community.

- Organized and taught an introductory LaTeX course on April 2021.

### Volunteer, Angeles de Guadalupe Foundation

- Supported the care of children and the preparation of their daily academic and didactic activities.

- Proposed and developed a didactic long-term project of didactic activities for the children, to be implemented in theFoundation beginning August 2019.

## Other training `r fa('school')`

- [Understanding and Visualizing Data with Python](https://coursera.org/share/386a614ccce4c470a91860c8761574e8)
- [Python Fundamentals](https://www.datacamp.com/statement-of-accomplishment/track/20727871220aa1029da98676a9c6384837bbf16b?raw=1)
- [Data Scientist Professional with R](https://www.datacamp.com/completed/statement-of-accomplishment/track/7959677023aa011ac70c4e310851efea40caaa7e)
- [Data Scientist with R](https://www.datacamp.com/statement-of-accomplishment/track/e4dc8d8e504e9a8876da63594f45c218ff6aff8b) - June 2023 (DataCamp^[See full list of certificates [here](https://docs.google.com/spreadsheets/d/1FyRoLfCxDTZWAc4KclG57NyAm4fQkSfWovXKHamNUgc/edit?usp=sharing)])
- [Data Visualization with R](https://www.datacamp.com/statement-of-accomplishment/track/6ef155d1b147de5b9ff882486ab6e4a8343235a8)- June 2023 (DataCamp)
- [SFU Big Data Hub Fellowships](https://drive.google.com/file/d/1-zv3u4XveY5OiWMSijBnOkGSj5xNtP4T/view?usp=sharing): AI Essentials - November 2022 (Simon Fraser University)
- [Statistics Fundamentals with R](https://www.datacamp.com/statement-of-accomplishment/track/ed7bf0109007d0465fab47b5742e00a4abda0ca1) - July 2022 (DataCamp)
- [Data Analyst with R](https://www.datacamp.com/statement-of-accomplishment/track/de49799dd48f4379a583a46a422360502d7f7f18) - June 2022 (DataCamp)
- [Power BI Fundamentals](https://www.datacamp.com/statement-of-accomplishment/track/29f31720f7778d93959273b7ffb3189de3ab8e9e) - June 2022 (DataCamp)
- [Tableau Fundamentals](https://www.datacamp.com/statement-of-accomplishment/track/de49799dd48f4379a583a46a422360502d7f7f18) - June 2022 (DataCamp)
- [Intermediate SQL](https://www.datacamp.com/statement-of-accomplishment/course/60cd712849c87d01191867fbce9c71cf33a84dda) - May 2022 (DataCamp)
- University Pathway Advanced English, ILSC Vancouver - August to November 2016