---
title: "Research"
---

```{r}
#| label: setup
#| include: false
library(fontawesome)
```

## Peer-reviewed publications

### [Honesty by Convenience: Corruption Tolerance in Ecuador](https://pressbooks.lib.vt.edu/pper/chapter/article-5/)

*Dedicated to the memory of Jorge Pazmiño (1941-2021)  `r fa('cross')`*

-  Sánchez Pazmiño, D. (2023). Honesty by Convenience: Corruption Tolerance in Ecuador. In
The Philosophy, Politics and Economics Review.
https://pressbooks.lib.vt.edu/app/uploads/sites/47/2023/03/PPER-Volume-2-2023.pdf.

- Capstone project presented for the obtainment of the Bachelor of Arts in Economics degree at USFQ. Awarded best USFQ undergraduate capstone project for the Fall 2021 semester by the USFQ School of Economics.  

- Working paper available [here](files/research/hbc-v2.pdf). Initial version submitted to USFQ capstone project's DSpace available [here](https://repositorio.usfq.edu.ec/handle/23000/11202). As of July 2022, a [GitHub repository](https://github.com/dsanchezp18/hbc-v2) includes the source code to reproduce all^[Except one graph, due to data copyright reasons, but I do share some code that can make this graph more or less reproducible for people with access to the data. See the repository for details.] of the paper's prose and data analysis.

### [Immunizing the Economy: A Causal Discussion on Vaccines and Economic Recovery](files/research/immunizing-the-econ.pdf)^[The publisher's [website](https://ojs.supercias.gob.ec/index.php/X-pedientes_Economicos/article/view/103) is often down, so I include a link to the published paper version.]

- Sánchez Pazmiño, D. H. (2022). Immunizing the Economy: A Causality Discussion on Vaccines and Economic Recovery. X-Pedientes Económicos, 6(14), 65–82. 

- Source code posted in a [GitHub repository](https://github.com/dsanchezp18/covidvax-econrecovery-paper) and an RMarkdown notebook posted in [RPubs](https://rpubs.com/dsanchezp998/covidvax).

## Non peer-reviewed publications^[See media for details on some of these publications]

- Quijano, A. & Sánchez, D. (2023). [*Homosexuality: what do Ecuadorians think about it?*](https://elquantificador.org/post/valores/2023-07-02-homosexualidad-qu-piensan-los-ecuatorianos/) (In Spanish). ISSN 2953-6456. Original title in Spanish: *Homosexualidad: ¿qué piensan los ecuatorianos?*

- Marchán, A. & Sánchez, D. (2023). [*Three problems for the quantitative analysis of femicides in Ecuador* (In Spanish)](https://elquantificador.org/post/valores/2023-03-07-tres-problemas-para-el-an-lisis-cuantitativo-de-los-femicidios-en-ecuador/). ISSN 2953-6456. Original title in Spanish: *Tres problemas para el análisis cuantitativo de los femicidios en Ecuador*.

- Sánchez, D. (2022). [*A quantitative perspective on the Ecuadorian protests*](https://elquantificador.org/post/valores/perspectiva-cuantitativa-protestas-ecuador/) (In Spanish). ISSN 2953-6456. Original title in Spanish: *Una perspectiva cuantitativa sobre las protestas en Ecuador*.
